name: DIP-Inv-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy=1.9.1
  - matplotlib=3.8.0
  - mkl
  - pip
  - pytorch=2.0.1
  - torchvision
  - geoana=0.4.0
  - pymatsolver=0.2.0
  - discretize=0.8.3
  - SimPEG=0.19.0

